CREATE TABLE ANIMAL (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR
);

INSERT INTO ANIMAL (ID, NAME) VALUES (1, 'Bengal Tiger');
INSERT INTO ANIMAL (ID, NAME) VALUES (2, 'Golden Retriever');
INSERT INTO ANIMAL (ID, NAME) VALUES (3, 'American Bobtail');